import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Inter } from 'next/font/google';
import '../globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: './favicon.ico',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
  team,
  analytics,
}: Readonly<{
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* <Header /> */}
        <AntdRegistry>
          <div className='container mx-auto p-6'>
            <div className='flex justify-center text-blue-500 gap-6'>
              <Link href='/'>Home</Link>
              <Link href='/visitors'>Visitors</Link>
            </div>
            <div className='flex gap-6'>
              {team}
              {analytics}
            </div>
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
